### PR TITLE
Add equals/hashCode implementations to the EntityGraph classes

### LINKED ISSUE #21: Equals and hashCode on AbstractEntityGraph?
This is maybe a question and maybe and issue - I ran into a problem where I had introduced this project as a dependency (thanks!) but mock calls were failing to match because I (incorrectly) assumed that `EntityGraphs.named("x").equals(EntityGraphs.named("x"))` is true. Is there a reason that equals and hashCode are not implemented? Would you accept a PR adding this to AbstractEntityGraph?

### PR DESCRIPTION
**Pull request by thyming**
Closes #21.

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Thank you @thyming .
Could you add tests on the two classes?

**Comment by thyming** [comment]
Sure thing, done.

**Comment by reda-alaoui** [comment]
Thank you @thyming 
I am releasing right now.

**Comment by thyming** [comment]
Thanks!

**Comment by reda-alaoui** [comment]
2.0.7 has been released.

**Pull request merged**
