### PR TITLE
return List instead of Iterable and adapt to new interface-hierarchy

### PR DESCRIPTION
**Pull request by fladdimir**
proposal for resolving https://github.com/Cosium/spring-data-jpa-entity-graph/issues/201

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Hi @fladdimir ,
Sorry for the time it took me to take a look. I am ok with your changes but we need to have a migration window. 

Would it be possible to not touch the current repository interfaces, and create new ones in a new `repository2` package? 

I want people to migrate incrementally if needed, by exposing 2 repository trees (the deprecated one and yours), until the next Spring major version.

**Review by reda-alaoui — CHANGES_REQUESTED** [review]
.

**Comment by fladdimir** [comment]
Hi @reda-alaoui, Thank you for the feedback!
I fully understand that the major version numbers should be kept in sync and thus a breaking change is not possible at the moment.
As the proposed change does not provide much functionality, it is probably not worth to introduce a whole new repository(2) interface tree / package?
As long as nothing more important/useful comes up, it might just be simpler to wait for the next spring-data-jpa major release?

**Comment by 4javier** [comment]
I apologize for commenting on a closed issue, but I cannot understand what's been the final word on this merge.
Related issue has been marked as wontfix, but it looks here like it's just been postponed.
Is there any release date?

**Pull request closed without merging**
